name: challenge_open_pass
description: A StarWars project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  flutter_hooks: ^0.18.2+1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  cached_network_image: ^3.3.0
  flutter_screenutil: ^5.9.0
  dartz: ^0.10.1
  build_runner: ^2.4.13
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family:  StarJedi
      fonts:
        - asset: assets/fonts/star_jedi_font/starjedi.ttf
          
    - family:  StarJhol
      fonts:
        - asset: assets/fonts/star_jedi_font/starjhol.ttf

    - family:  StJediSe
      fonts:
        - asset: assets/fonts/star_jedi_font/stjedise.ttf     

    - family:  StarJourt
      fonts:
        - asset: assets/fonts/star_jourt_font/starjout.ttf

  assets:
    - assets/
